resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_suthapai
    name: suthapai/Demo-infra-as-code
variables:
  - group: vnet-variables
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: create_vnet
  jobs:
  - job: create_vnet_job
    displayName: Create Virtual Network
    steps:
    - checkout: MyGitHubRepo
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v-net'
        backendServiceArm: 'Azureportal-devops-sc'
        backendAzureRmResourceGroupName: 'rg-tfstate'
        backendAzureRmStorageAccountName: 'sgtfstatefile'
        backendAzureRmContainerName: 'mytfstate'
        backendAzureRmKey: 'vnet.tfstate'
  
