resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_suthapai
    name: suthapai/Demo-infra-as-code
variables:
  - group: vnet-variables
  - group: vm-variables
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: create_vnet
  jobs:
  - job: create_vnet_job
    displayName: Create Virtual Network
    steps:
    - checkout: MyGitHubRepo
    - task: TerraformInstaller@1
      inputs:
         terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: Terraform Init_vnet
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v-net'
        backendServiceArm: 'Azureportal-devops-sc'
        backendAzureRmResourceGroupName: 'rg-tfstate'
        backendAzureRmStorageAccountName: 'sgtfstatefile'
        backendAzureRmContainerName: 'mytfstate'
        backendAzureRmKey: 'vnet1.tfstate'
    - task: TerraformTaskV4@4
      displayName: Terraform Apply_vnet
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/v-net'
        environmentServiceNameAzureRM: 'Azureportal-devops-sc'
   
    # - task: TerraformTaskV4@4
    #   displayName: Terraform Destroy
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'destroy'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/v-net'
    #     environmentServiceNameAzureRM: 'Azureportal-devops-sc'
        
- stage: create_vm
  dependsOn: create_vnet
  jobs:
  - job: create_vm_agent_pool
    displayName: CreateVM
    steps:
      - checkout: MyGitHubRepo
      - task: TerraformInstaller@1
        inputs:
         terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        displayName: Terraform init_vm
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/agent-vm'
          backendServiceArm: 'Azureportal-devops-sc'
          backendAzureRmResourceGroupName: 'rg-tfstate'
          backendAzureRmStorageAccountName: 'sgtfstatefile'
          backendAzureRmContainerName: 'mytfstate'
          backendAzureRmKey: 'vnet1.tfstate'
     
      - task: TerraformTaskV4@4
        displayName: Terraform apply_vm
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'Azureportal-devops-sc'
          workingDirectory: '$(System.DefaultWorkingDirectory)/agent-vm'